services:
  rentalx-pg-db:
    image: bitnami/postgresql
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=ignite
      - POSTGRESQL_DATABASE=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    network_mode: host

volumes:
  pgdata:
    driver: local

# networks:
#   my-network:
#     external: true