###
GET http://localhost:3333/cars


### query ==> brand, name, categoryId
GET http://localhost:3333/cars/available

###
POST http://localhost:3333/cars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTAyMjMyMzQsImV4cCI6MTY5MDMwOTYzNCwic3ViIjoiNzg4OWVkMWUtMWVlMy00ZmZmLWJjOTAtMmE0NmVkNmYyOGEwIn0.-tV2xBoqfvISN3qJsWLUY3J6dIeLz6pnTfi7mcnm9gc
Content-Type: application/json

{
  "brand": "Audi",
  "categoryId": "97a5753a-dc33-4e22-a66c-c5ee40b65cb7",
  "dailyRate": 140,
  "description": "Carro bonito",
  "fineAmount": 100,
  "licensePlate": "DEF-1212",
  "name": "Audi A4"
}

### Bearer token admin
POST http://localhost:3333/cars/specifications/1894a2a9-6fff-4bab-87ef-d859ac1db0d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTAxMjE1ODgsImV4cCI6MTY5MDIwNzk4OCwic3ViIjoiNzg4OWVkMWUtMWVlMy00ZmZmLWJjOTAtMmE0NmVkNmYyOGEwIn0.IcaXk0LgXnOuaGHyRZQT3JTgWR-XSyAx5o6hLvI3exo
Content-Type: application/json

{
  "specificationsId": [
    "2db1751a-3de9-4b09-b164-1205992d74b5"
  ]
}