###
POST http://localhost:3333/password/forgot
Content-Type: application/json

{
  "email": "teste@email.com"
}

###
POST http://localhost:3333/password/reset?token=89c18116-f528-4f89-a138-90e2a1279078
Content-Type: application/json

{
  "password": "123456"
}