###
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTEwMDU2OTYsImV4cCI6MTY5MTAwNjU5Niwic3ViIjoiNzg4OWVkMWUtMWVlMy00ZmZmLWJjOTAtMmE0NmVkNmYyOGEwIn0._20uxLV3QSPBfty_s9gtW9PgILso-VqvDEHLnsCLR3w

###
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Alan Junqueira",
  "email": "teste@email.com",
  "password": "1234",
  "driverLicense": "123456"
}

###
POST http://15.229.9.117/users
Content-Type: application/json

{
  "name": "Alan Junqueira",
  "email": "teste@email.com",
  "password": "1234",
  "driverLicense": "123456"
}

### Updte user avatar
PATCH http://localhost:3333/users/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTEwMDU2OTYsImV4cCI6MTY5MTAwNjU5Niwic3ViIjoiNzg4OWVkMWUtMWVlMy00ZmZmLWJjOTAtMmE0NmVkNmYyOGEwIn0._20uxLV3QSPBfty_s9gtW9PgILso-VqvDEHLnsCLR3w
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="profile.png"
Content-Type: image/png

< ./profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


